### ISSUE TITLE
With Deal colorings, color should account for overhead

### ISSUE THREAD

**Issue by dhouck** [worldwidewaves/Cookie-Stonks#1]
It's late so I might have the math wrong here, but the general point should be right.  Buying at just below the resting price and selling at just above doesn't get any profits, because the overhead eats it all.  If we let _o_ be overhead (so without brokers, overhead is 20% and _o_ = 0.2), then if the stock percentage value is between 1/sqrt(1 + _o_) and sqrt(1 + _o_), it should be colored gray in deal mode; then you can always buy purple-colored stocks and sell green-colored ones without losing anything to overhead.

**Comment by dhouck** [comment]
Thanks!  This will make things easier, especially early in a run.

**Comment by worldwidewaves** [comment]
Sure! Let me know if I messed up anything or something doesn't work as intended.

**Comment by dhouck** [comment]
I'm still seeing some issue but I'm not sure exactly where it's coming from.  My overhead is 1.54%, so with the symmetric calculation I suggested nothing should happen between about 99.24% and 100.77%.  However, in this screenshot:
![Screenshot 2021-03-15 at 5 54 13 PM](https://user-images.githubusercontent.com/524925/111236398-01733d80-85b0-11eb-9fb9-e389f0a3ef6a.png)
it says I should sell at something rounded *up* to 100%.  That is, the ratio is within the no-action range, and even with no overhead it's below 100% so should not be a sell color.

Unfortunately, since I took the screenshot the market's changed and I can't test with the other gradient scheme or try to debug the code in the js console, or I'd provide more information.

**Comment by worldwidewaves** [comment]
Hmm... I've been looking into it a bit but can't replicate it so far, if i change the values to percentage = 100% and overhead = 1.54% it does indeed stay greyed out.

There might be some problem with it not updating when the market updates, I'll keep an eye on it.
