### ISSUE TITLE
[Feature Request] Add support for publicists added in 2.048

### ISSUE THREAD

**Issue by TheBeardOfTruth** [worldwidewaves/Cookie-Stonks#11]
Simple enough FR, currently as of Cookie Stonks 1.7.2 publicist stocks aren't affected by cookie stonks.

**Comment by worldwidewaves** [comment]
but they are tho 🤔
<img width="153" alt="Screenshot_19" src="https://user-images.githubusercontent.com/17983606/174160446-2b8510f6-e1b2-465b-ad45-ae271624dfdd.png">
Since commit https://github.com/worldwidewaves/Cookie-Stonks/commit/b6a52f7d9cf09a060dd9ff28d7ff533f98c9b9d9

**Comment by TheBeardOfTruth** [comment]
Not on my end, and I should be using the newest commit on the master branch.

![Screenshot_2022-06-17_03-36-19](https://user-images.githubusercontent.com/53689060/174204982-7d549f45-bd2e-4cae-bfd5-716df6fde425.png)


Guess something's wrong on my end though, I'll see if I can't get it resolved by removing the userscript entirely, reloading to ensure it's fully unloaded, and then re-adding it.
