### ISSUE TITLE
Bookmark link doesnt seem to work

### ISSUE THREAD

**Issue by MrTomatosoup** [worldwidewaves/Cookie-Stonks#12]
New to GitHub, don't know if I'm doing this correctly. 

I use the [CookieClickerModManager](https://github.com/klattmose/CookieClickerModManager), and Cookie stonks won't load. When I try using the normal “bookmark method” as described under installation, the mod won't load either. Could there be something wrong with the url? I am using: "https://combinatronics.com/worldwidewaves/Cookie-Stonks/main/main.user.js"  

Thanks for any advice!

**Comment by worldwidewaves** [comment]
The website seems to be down, try using [https://worldwidewaves.github.io/Cookie-Stonks/main.user.js](https://worldwidewaves.github.io/Cookie-Stonks/main.user.js)

**Comment by MrTomatosoup** [comment]
> The website seems to be down, try using https://worldwidewaves.github.io/Cookie-Stonks/main.user.js

This works, thanks for the reply!
