### ISSUE TITLE
Is a Steam port coming any time soon?

### ISSUE THREAD

**Issue by rauldrac** [worldwidewaves/Cookie-Stonks#3]
It's a great mod for people like me who don't understand anything about the stock market, so I was wondering if it would be receiving a port any time soon.

**Comment by lucscamps** [comment]
Pleeeaaase? <3

**Comment by worldwidewaves** [comment]
mmm maybee 🤔🤔

**Comment by VictorS8** [comment]
I hope so!

**Comment by Benna96** [comment]
Hey, happened to make a Steam port. I moved everything inside Game.registerMod, since I was worried about global variables, and removed the eventlistener for load, it wasn't triggering. Should I upload the zip here?
Edit: Made a pull request.

**Comment by worldwidewaves** [comment]
Hey thanks a lot Benna! i've just merged your request -i'll keep the issue open for a few days to see if everyone is able to install it and whatnot

> To **install the Steam version** simply follow the instructions provided by Benna in the [README](https://github.com/suicidejerk/Cookie-Stonks)

cheers 👍

**Comment by VictorS8** [comment]
Worked very well! Good work, @Benna96 👍
@suicidejerk +1 tested and validate "issue" haha

Do you know about "Third-party" shadow achievement is working on steam version? Did not pop up for me
Maybe they didn't add to steam version, so if anyone knows about it, I'd appreciate it if you let me know

**Comment by Benna96** [comment]
Hmm... looking at the source code, there's this line: ```if (!App && Game.Win) Game.Win('Third-party');```
App stands for Steam version.
So it would seem the game doesn't automatically give the achievement on Steam. A mod needs to specifically give it.

**Comment by VictorS8** [comment]
Like "Cheat achievement" on wiki says that is not available on steam, so this achievement may be not available on steam either? Or maybe I miss understood your comment

**Comment by Benna96** [comment]
It is available, I have it and I only play Steam.
The way it works on browser is, if the game detects any addons at all, it'll give you the achievement.
However, on Steam, the game does not give you the achievement. A mod needs to be coded in such a way that it has the line ```Game.Win('Third-party');``` in it somewhere, and Cookie Stonks currently does not have such a line.

**Comment by VictorS8** [comment]
Ahh I understood it now! Thank you 👍
