### ISSUE TITLE
Save was completely frozen.

### ISSUE THREAD

**Issue by IrateClicker** [worldwidewaves/Cookie-Stonks#7]
The last thing I needed was for this thing to completely freeze my save. Now I can't do a flipping thing on cookie clicker, because the whole website was frozen as soon as I clicked on the bookmark. I followed the instructions to the letter, and still it froze. I closed and reopened the tab. Still frozen. I got rid of the bookmark. Still frozen. I shutdown and restarted my computer. STILL FROZEN. Now, I'm sure this is nobody's fault, and I'm sure you can understand as well that I'm incredibly frustrated at the moment due to this seemingly inexplicable issue. A response of any kind, even telling me to shut up, would be appreciated.

**Comment by worldwidewaves** [comment]
That's very odd, specially considering this mod does NOT use your savefile for anything.
Try clearing your browser cache, do NOT delete your browser cookies or you'll lose your savefile.

Also can you press F12 and see what it says on the console?
