### ISSUE TITLE
Makes the cookies from cookie storms fly off of the screen

### ISSUE THREAD

**Issue by worldwidewaves** [worldwidewaves/Cookie-Stonks#9]
More info: https://steamcommunity.com/sharedfiles/filedetails/?id=2767659541

**Comment by Nnnes** [comment]
https://github.com/worldwidewaves/Cookie-Stonks/blob/3d912a246f4daf179704f6366a519e3432c348f9/main.user.js#L44-L50

Removing the `position: relative;` here fixes the issue. It appears that nothing in Cookie Stonks uses `.shimmer` at all, so maybe remove the whole block?

**Comment by worldwidewaves** [comment]
Yep just found that out too, I'll update it once (with a few language fixes too) if i can manage to test it on the Steam version (right now I can't get the base version to start up for some reason).
